name: qa terraform w/ oidc
on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

jobs:
  qa-plan:
    uses: ./.github/workflows/reusable-terraform-workflow.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: qa
      region: us-west-2
    secrets: 
      aws_role: ${{ secrets.AWS_ROLE_QA }}